apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcostlab-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcostlab-backend
  template:
    metadata:
      labels:
        app: cloudcostlab-backend
    spec:
      containers:
        - name: backend
          image: cloudcostlab-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg2://gaussdb:CloudGauss%402026@opengauss:5432/postgres
            - name: AUTO_SEED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudcostlab-backend
spec:
  selector:
    app: cloudcostlab-backend
  ports:
    - port: 8000
      targetPort: 8000
