apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opengauss
spec:
  serviceName: opengauss
  replicas: 1
  selector:
    matchLabels:
      app: opengauss
  template:
    metadata:
      labels:
        app: opengauss
    spec:
      containers:
        - name: opengauss
          image: docker.m.daocloud.io/enmotech/opengauss:3.0.0
          securityContext:
            privileged: true
          ports:
            - containerPort: 5432
          env:
            - name: GS_USERNAME
              value: gaussdb
            - name: GS_PASSWORD
              value: CloudGauss@2026
            - name: GS_PORT
              value: "5432"
          volumeMounts:
            - name: data
              mountPath: /var/lib/opengauss/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opengauss
spec:
  selector:
    app: opengauss
  ports:
    - port: 5432
      targetPort: 5432
